services:
    chat:
        name: chat.heboba.dev
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - NODE_ENV=production
            - PORT=3000
            - HOSTNAME=0.0.0.0
        labels:
            - "traefik.enable=true"
            # Router
            - "traefik.http.routers.${TRAEFIK_ROUTER_NAME}.rule=Host(`${SITE_HOST}`)"
            - "traefik.http.routers.${TRAEFIK_ROUTER_NAME}.entrypoints=websecure"
            - "traefik.http.routers.${TRAEFIK_ROUTER_NAME}.tls=true"
            - "traefik.http.routers.${TRAEFIK_ROUTER_NAME}.tls.certresolver=letsencrypt"
            - "traefik.http.services.${TRAEFIK_ROUTER_NAME}.loadbalancer.server.port=${INTERNAL_PORT}"
        networks:
            - web

networks:
    web:
        external: true
        name: web
