services:
    chat:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                BUILD_DIR: dist
        ports:
            - "${DEV_PORT}:80"
        restart: unless-stopped
