name: Deploy to Prod

on:
    push:
        branches: ["main"]

jobs:
    deploy:
        runs-on: ubuntu-latest
        environment: PROD

        steps:
            - name: Checkout (optional)
              uses: actions/checkout@v4

            - name: Sanity check secrets
              run: |
                  test -n "${{ secrets.SSH_HOST }}" || (echo "::error ::SSH_HOST is empty"; exit 1)
                  test -n "${{ secrets.SSH_USER }}" || (echo "::error ::SSH_USER is empty"; exit 1)
                  test -n "${{ secrets.SSH_KEY  }}" || (echo "::error ::SSH_KEY is empty";  exit 1)
                  echo "OK: secrets are present"

            - name: Deploy over SSH
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USER }}
                  key: ${{ secrets.SSH_KEY }}
                  port: ${{ secrets.SSH_PORT }}
                  script_stop: true
                  script: |
                      set -e
                      cd /home/deploy/projects/chat.heboba.dev
                      git fetch --all
                      git reset --hard origin/main

                      export SITE_HOST=${{ secrets.SITE_HOST }}
                      export INTERNAL_PORT=3000

                      # build and deploy
                      docker compose -f docker-compose.yml -f docker-compose.prod.yml build --no-cache
                      docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d --remove-orphans

                      # cleanup
                      docker image prune -f
